app = "whatsapp-ai-assistant"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3030"
  NODE_ENV = "production"

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
