services:
  - type: web
    name: whatsapp-ai-assistant
    env: node
    buildCommand: npm install
    startCommand: node whatsapp-ai-assistant-universal.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
